export const SET_AUTH_LOADING = "SET_AUTH_LOADING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const GET_ALL_EMPLOYEES_SUCCESS = "GET_ALL_EMPLOYEES_SUCCESS";
export const GET_ALL_EMPLOYEES_FAILURE = "GET_ALL_EMPLOYEES_FAILURE";

export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE_FAILURE = "GET_EMPLOYEE_FAILURE";

export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_fAILURE";

export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_FAILURE = "UPDATE_EMPLOYEE_FAILURE";

export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAILURE = "DELETE_EMPLOYEE_FAILURE";

export const SET_FULL_SCREEN_LOADER_TRUE = "SET_FULL_SCREEN_LOADER_TRUE";
export const SET_FULL_SCREEN_LOADER_FALSE = "SET_FULL_SCREEN_LOADER_FALSE";

export const SET_SHOW_MODAL_TRUE = "SET_SHOW_MODAL_TRUE";
export const SET_SHOW_MODAL_FALSE = "SET_SHOW_MODAL_FALSE";

export const SET_MODAL_UPDATE_EMPLOYEE_DATA = "SET_MODAL_UPDATE_EMPLOYEE_DATA";
export const CLEAR_MODAL_UPDATE_EMPLOYEE_DATA =
  "CLEAR_MODAL_UPDATE_EMPLOYEE_DATA";

export const SET_MODAL_EMPLOYEE_DATA = "SET_MODAL_EMPLOYEE_DATA";
export const CLEAR_MODAL_EMPLOYEE_DATA = "CLEAR_MODAL_EMPLOYEE_DATA";
